server:
  port: 8082
Spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/products?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
    username: root
    password:
